X <- read.table("./household_power_consumption.txt", sep = ";", as.is = TRUE, na.strings = "?", header=TRUE)
X$Date <- as.Date(X$Date, "%d/%m/%Y")
data <- subset(X, Date == "2007-02-01" | Date == "2007-02-02")

png("plot4.png")
par(mfrow=c(2,2))
with(data, {plot(strptime(paste(Date,Time),"%Y-%m-%d %H:%M:%S"),Global_active_power,type='l',xlab="",ylab = 'Global Active Power')
            plot(strptime(paste(Date,Time),"%Y-%m-%d %H:%M:%S"),Voltage,type='l',xlab="datetime",ylab = 'Voltage')
            plot(strptime(paste(Date,Time),"%Y-%m-%d %H:%M:%S"), Sub_metering_1, type ="l", xlab ="", ylab="Energy sub metering")
            points(strptime(paste(Date,Time),"%Y-%m-%d %H:%M:%S"),Sub_metering_2, type ="l", col = "red")
            points(strptime(paste(Date,Time),"%Y-%m-%d %H:%M:%S"),Sub_metering_3, type ="l", col = "blue")
            legend("topright", col = c("black", "red","blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd=1)
            plot(strptime(paste(Date,Time),"%Y-%m-%d %H:%M:%S"),Global_reactive_power,type='l',xlab="datetime")})
dev.off()