X <- read.table("./household_power_consumption.txt", sep = ";", as.is = TRUE, na.strings = "?", header=TRUE)
X$Date <- as.Date(X$Date, "%d/%m/%Y")
data <- subset(X, Date == "2007-02-01" | Date == "2007-02-02")

png("plot3.png")
with(data, plot(strptime(paste(Date,Time),"%Y-%m-%d %H:%M:%S"), Sub_metering_1, type ="l", xlab ="", ylab="Energy sub metering"))
with(data, points(strptime(paste(Date,Time),"%Y-%m-%d %H:%M:%S"),Sub_metering_2, type ="l", col = "red"))
with(data, points(strptime(paste(Date,Time),"%Y-%m-%d %H:%M:%S"),Sub_metering_3, type ="l", col = "blue"))
legend("topright", col = c("black", "red","blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd=1)
dev.off()